apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: django
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx
  selector:
    {{- include "django.selectorLabels" . | nindent 4 }}
