---
# Gunicorn
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: app
  name: django-example-app-svc
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: app

---
# Database
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: django-example-db
spec:
  type: ClusterIP
  ports:
  - name: psql
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: db