apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: django-api

build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    push: true
  artifacts:
  - image: 127.0.0.1:5000/django-api
    docker:
      dockerfile: containers/app/Dockerfile
    sync:
      infer:
        - "**/*"
        - "*"

# Custom port forwards
portForward:
- resourceType: deployment
  resourceName: app
  namespace: django-kustomize
  port: 8000
- resourceType: deployment
  resourceName: db
  namespace: django-kustomize
  port: 5432

deploy:
  kustomize:
    paths:
    - "k8s/kustomize/overlays/minikube"