apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django-kustomize

resources:
  - ing.yaml

patchesStrategicMerge:
  - deploy.yaml
  - cm.yaml

bases:
  - ../../base

secretGenerator:
  - name: django-example-db
    literals:
      - password=password